// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.4
// source: service.proto

package proto_go

import (
	user "Pokemon/proto_go/user"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PokemonClient is the client API for Pokemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokemonClient interface {
	Login(ctx context.Context, in *user.LoginRequestMsg, opts ...grpc.CallOption) (*user.LoginResponseMsg, error)
	Register(ctx context.Context, in *user.RegisterRequestMsg, opts ...grpc.CallOption) (*NilResponseMsg, error)
}

type pokemonClient struct {
	cc grpc.ClientConnInterface
}

func NewPokemonClient(cc grpc.ClientConnInterface) PokemonClient {
	return &pokemonClient{cc}
}

func (c *pokemonClient) Login(ctx context.Context, in *user.LoginRequestMsg, opts ...grpc.CallOption) (*user.LoginResponseMsg, error) {
	out := new(user.LoginResponseMsg)
	err := c.cc.Invoke(ctx, "/pokemon.Pokemon/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokemonClient) Register(ctx context.Context, in *user.RegisterRequestMsg, opts ...grpc.CallOption) (*NilResponseMsg, error) {
	out := new(NilResponseMsg)
	err := c.cc.Invoke(ctx, "/pokemon.Pokemon/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokemonServer is the server API for Pokemon service.
// All implementations must embed UnimplementedPokemonServer
// for forward compatibility
type PokemonServer interface {
	Login(context.Context, *user.LoginRequestMsg) (*user.LoginResponseMsg, error)
	Register(context.Context, *user.RegisterRequestMsg) (*NilResponseMsg, error)
	mustEmbedUnimplementedPokemonServer()
}

// UnimplementedPokemonServer must be embedded to have forward compatible implementations.
type UnimplementedPokemonServer struct {
}

func (UnimplementedPokemonServer) Login(context.Context, *user.LoginRequestMsg) (*user.LoginResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedPokemonServer) Register(context.Context, *user.RegisterRequestMsg) (*NilResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPokemonServer) mustEmbedUnimplementedPokemonServer() {}

// UnsafePokemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokemonServer will
// result in compilation errors.
type UnsafePokemonServer interface {
	mustEmbedUnimplementedPokemonServer()
}

func RegisterPokemonServer(s grpc.ServiceRegistrar, srv PokemonServer) {
	s.RegisterService(&Pokemon_ServiceDesc, srv)
}

func _Pokemon_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.LoginRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokemon.Pokemon/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServer).Login(ctx, req.(*user.LoginRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pokemon_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(user.RegisterRequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokemon.Pokemon/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServer).Register(ctx, req.(*user.RegisterRequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Pokemon_ServiceDesc is the grpc.ServiceDesc for Pokemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pokemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon.Pokemon",
	HandlerType: (*PokemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Pokemon_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Pokemon_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
