// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: item/item.proto

package item

import (
	server "Pokemon/proto_go/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *server.Language       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      *ItemCategory          `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description   *server.Language       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Max           int32                  `protobuf:"varint,5,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Item) GetName() *server.Language {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Item) GetCategory() *ItemCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Item) GetDescription() *server.Language {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Item) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_item_item_proto protoreflect.FileDescriptor

const file_item_item_proto_rawDesc = "" +
	"\n" +
	"\x0fitem/item.proto\x12\apokemon\x1a\x15server/language.proto\x1a\x18item/item_category.proto\"\xb9\x01\n" +
	"\x04Item\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12$\n" +
	"\x04name\x18\x02 \x01(\v2\x10.server.LanguageR\x04name\x121\n" +
	"\bcategory\x18\x03 \x01(\v2\x15.pokemon.ItemCategoryR\bcategory\x122\n" +
	"\vdescription\x18\x04 \x01(\v2\x10.server.LanguageR\vdescription\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x05R\x03maxB\x17Z\x15Pokemon/proto_go/itemb\x06proto3"

var (
	file_item_item_proto_rawDescOnce sync.Once
	file_item_item_proto_rawDescData []byte
)

func file_item_item_proto_rawDescGZIP() []byte {
	file_item_item_proto_rawDescOnce.Do(func() {
		file_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)))
	})
	return file_item_item_proto_rawDescData
}

var file_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_item_item_proto_goTypes = []any{
	(*Item)(nil),            // 0: pokemon.Item
	(*server.Language)(nil), // 1: server.Language
	(*ItemCategory)(nil),    // 2: pokemon.ItemCategory
}
var file_item_item_proto_depIdxs = []int32{
	1, // 0: pokemon.Item.name:type_name -> server.Language
	2, // 1: pokemon.Item.category:type_name -> pokemon.ItemCategory
	1, // 2: pokemon.Item.description:type_name -> server.Language
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_item_item_proto_init() }
func file_item_item_proto_init() {
	if File_item_item_proto != nil {
		return
	}
	file_item_item_category_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_item_item_proto_goTypes,
		DependencyIndexes: file_item_item_proto_depIdxs,
		MessageInfos:      file_item_item_proto_msgTypes,
	}.Build()
	File_item_item_proto = out.File
	file_item_item_proto_goTypes = nil
	file_item_item_proto_depIdxs = nil
}
