// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/pokemon.proto

package pokemon

import (
	server "Pokemon/proto_go/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pokemon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *server.Language       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          float32                `protobuf:"fixed32,3,opt,name=size,proto3" json:"size,omitempty"`
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	mi := &file_pokemon_pokemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_pokemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_pokemon_pokemon_proto_rawDescGZIP(), []int{0}
}

func (x *Pokemon) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Pokemon) GetName() *server.Language {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Pokemon) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pokemon) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_pokemon_pokemon_proto protoreflect.FileDescriptor

const file_pokemon_pokemon_proto_rawDesc = "" +
	"\n" +
	"\x15pokemon/pokemon.proto\x12\apokemon\x1a\x15server/language.proto\"o\n" +
	"\aPokemon\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12$\n" +
	"\x04name\x18\x02 \x01(\v2\x10.server.LanguageR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x02R\x04size\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weightB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_pokemon_proto_rawDescOnce sync.Once
	file_pokemon_pokemon_proto_rawDescData []byte
)

func file_pokemon_pokemon_proto_rawDescGZIP() []byte {
	file_pokemon_pokemon_proto_rawDescOnce.Do(func() {
		file_pokemon_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_proto_rawDesc), len(file_pokemon_pokemon_proto_rawDesc)))
	})
	return file_pokemon_pokemon_proto_rawDescData
}

var file_pokemon_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_pokemon_proto_goTypes = []any{
	(*Pokemon)(nil),         // 0: pokemon.Pokemon
	(*server.Language)(nil), // 1: server.Language
}
var file_pokemon_pokemon_proto_depIdxs = []int32{
	1, // 0: pokemon.Pokemon.name:type_name -> server.Language
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pokemon_pokemon_proto_init() }
func file_pokemon_pokemon_proto_init() {
	if File_pokemon_pokemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_proto_rawDesc), len(file_pokemon_pokemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_pokemon_proto_goTypes,
		DependencyIndexes: file_pokemon_pokemon_proto_depIdxs,
		MessageInfos:      file_pokemon_pokemon_proto_msgTypes,
	}.Build()
	File_pokemon_pokemon_proto = out.File
	file_pokemon_pokemon_proto_goTypes = nil
	file_pokemon_pokemon_proto_depIdxs = nil
}
