// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/pokemon_spawn.proto

package pokemon

import (
	server "Pokemon/proto_go/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonSpawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pokemon       *Pokemon               `protobuf:"bytes,2,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	Map           *server.Map            `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	Probability   float32                `protobuf:"fixed32,4,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonSpawn) Reset() {
	*x = PokemonSpawn{}
	mi := &file_pokemon_pokemon_spawn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonSpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonSpawn) ProtoMessage() {}

func (x *PokemonSpawn) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_pokemon_spawn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonSpawn.ProtoReflect.Descriptor instead.
func (*PokemonSpawn) Descriptor() ([]byte, []int) {
	return file_pokemon_pokemon_spawn_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonSpawn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PokemonSpawn) GetPokemon() *Pokemon {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *PokemonSpawn) GetMap() *server.Map {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *PokemonSpawn) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

var File_pokemon_pokemon_spawn_proto protoreflect.FileDescriptor

const file_pokemon_pokemon_spawn_proto_rawDesc = "" +
	"\n" +
	"\x1bpokemon/pokemon_spawn.proto\x12\apokemon\x1a\x15pokemon/pokemon.proto\x1a\x10server/map.proto\"\x8f\x01\n" +
	"\fPokemonSpawn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\apokemon\x18\x02 \x01(\v2\x10.pokemon.PokemonR\apokemon\x12\x1d\n" +
	"\x03map\x18\x03 \x01(\v2\v.server.MapR\x03map\x12 \n" +
	"\vprobability\x18\x04 \x01(\x02R\vprobabilityB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_pokemon_spawn_proto_rawDescOnce sync.Once
	file_pokemon_pokemon_spawn_proto_rawDescData []byte
)

func file_pokemon_pokemon_spawn_proto_rawDescGZIP() []byte {
	file_pokemon_pokemon_spawn_proto_rawDescOnce.Do(func() {
		file_pokemon_pokemon_spawn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_spawn_proto_rawDesc), len(file_pokemon_pokemon_spawn_proto_rawDesc)))
	})
	return file_pokemon_pokemon_spawn_proto_rawDescData
}

var file_pokemon_pokemon_spawn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_pokemon_spawn_proto_goTypes = []any{
	(*PokemonSpawn)(nil), // 0: pokemon.PokemonSpawn
	(*Pokemon)(nil),      // 1: pokemon.Pokemon
	(*server.Map)(nil),   // 2: server.Map
}
var file_pokemon_pokemon_spawn_proto_depIdxs = []int32{
	1, // 0: pokemon.PokemonSpawn.pokemon:type_name -> pokemon.Pokemon
	2, // 1: pokemon.PokemonSpawn.map:type_name -> server.Map
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pokemon_pokemon_spawn_proto_init() }
func file_pokemon_pokemon_spawn_proto_init() {
	if File_pokemon_pokemon_spawn_proto != nil {
		return
	}
	file_pokemon_pokemon_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_spawn_proto_rawDesc), len(file_pokemon_pokemon_spawn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_pokemon_spawn_proto_goTypes,
		DependencyIndexes: file_pokemon_pokemon_spawn_proto_depIdxs,
		MessageInfos:      file_pokemon_pokemon_spawn_proto_msgTypes,
	}.Build()
	File_pokemon_pokemon_spawn_proto = out.File
	file_pokemon_pokemon_spawn_proto_goTypes = nil
	file_pokemon_pokemon_spawn_proto_depIdxs = nil
}
