// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/pokemon_skill_relation.proto

package pokemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonSkillRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pokemon       *Pokemon               `protobuf:"bytes,2,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	Skill         *Skill                 `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonSkillRelation) Reset() {
	*x = PokemonSkillRelation{}
	mi := &file_pokemon_pokemon_skill_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonSkillRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonSkillRelation) ProtoMessage() {}

func (x *PokemonSkillRelation) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_pokemon_skill_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonSkillRelation.ProtoReflect.Descriptor instead.
func (*PokemonSkillRelation) Descriptor() ([]byte, []int) {
	return file_pokemon_pokemon_skill_relation_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonSkillRelation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PokemonSkillRelation) GetPokemon() *Pokemon {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *PokemonSkillRelation) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *PokemonSkillRelation) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_pokemon_pokemon_skill_relation_proto protoreflect.FileDescriptor

const file_pokemon_pokemon_skill_relation_proto_rawDesc = "" +
	"\n" +
	"$pokemon/pokemon_skill_relation.proto\x12\apokemon\x1a\x15pokemon/pokemon.proto\x1a\x13pokemon/skill.proto\"\x92\x01\n" +
	"\x14PokemonSkillRelation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\apokemon\x18\x02 \x01(\v2\x10.pokemon.PokemonR\apokemon\x12$\n" +
	"\x05skill\x18\x03 \x01(\v2\x0e.pokemon.SkillR\x05skill\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05levelB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_pokemon_skill_relation_proto_rawDescOnce sync.Once
	file_pokemon_pokemon_skill_relation_proto_rawDescData []byte
)

func file_pokemon_pokemon_skill_relation_proto_rawDescGZIP() []byte {
	file_pokemon_pokemon_skill_relation_proto_rawDescOnce.Do(func() {
		file_pokemon_pokemon_skill_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_skill_relation_proto_rawDesc), len(file_pokemon_pokemon_skill_relation_proto_rawDesc)))
	})
	return file_pokemon_pokemon_skill_relation_proto_rawDescData
}

var file_pokemon_pokemon_skill_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_pokemon_skill_relation_proto_goTypes = []any{
	(*PokemonSkillRelation)(nil), // 0: pokemon.PokemonSkillRelation
	(*Pokemon)(nil),              // 1: pokemon.Pokemon
	(*Skill)(nil),                // 2: pokemon.Skill
}
var file_pokemon_pokemon_skill_relation_proto_depIdxs = []int32{
	1, // 0: pokemon.PokemonSkillRelation.pokemon:type_name -> pokemon.Pokemon
	2, // 1: pokemon.PokemonSkillRelation.skill:type_name -> pokemon.Skill
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pokemon_pokemon_skill_relation_proto_init() }
func file_pokemon_pokemon_skill_relation_proto_init() {
	if File_pokemon_pokemon_skill_relation_proto != nil {
		return
	}
	file_pokemon_pokemon_proto_init()
	file_pokemon_skill_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_skill_relation_proto_rawDesc), len(file_pokemon_pokemon_skill_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_pokemon_skill_relation_proto_goTypes,
		DependencyIndexes: file_pokemon_pokemon_skill_relation_proto_depIdxs,
		MessageInfos:      file_pokemon_pokemon_skill_relation_proto_msgTypes,
	}.Build()
	File_pokemon_pokemon_skill_relation_proto = out.File
	file_pokemon_pokemon_skill_relation_proto_goTypes = nil
	file_pokemon_pokemon_skill_relation_proto_depIdxs = nil
}
