// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/pokemon_inventory_skill_relation.proto

package pokemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonInventorySkillRelation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PokemonInventory *PokemonInventory      `protobuf:"bytes,2,opt,name=pokemon_inventory,json=pokemonInventory,proto3" json:"pokemon_inventory,omitempty"`
	Skill            *Skill                 `protobuf:"bytes,3,opt,name=skill,proto3" json:"skill,omitempty"`
	PowerPoint       int32                  `protobuf:"varint,4,opt,name=power_point,json=powerPoint,proto3" json:"power_point,omitempty"`
	Use              int32                  `protobuf:"varint,5,opt,name=use,proto3" json:"use,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PokemonInventorySkillRelation) Reset() {
	*x = PokemonInventorySkillRelation{}
	mi := &file_pokemon_pokemon_inventory_skill_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonInventorySkillRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonInventorySkillRelation) ProtoMessage() {}

func (x *PokemonInventorySkillRelation) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_pokemon_inventory_skill_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonInventorySkillRelation.ProtoReflect.Descriptor instead.
func (*PokemonInventorySkillRelation) Descriptor() ([]byte, []int) {
	return file_pokemon_pokemon_inventory_skill_relation_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonInventorySkillRelation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PokemonInventorySkillRelation) GetPokemonInventory() *PokemonInventory {
	if x != nil {
		return x.PokemonInventory
	}
	return nil
}

func (x *PokemonInventorySkillRelation) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

func (x *PokemonInventorySkillRelation) GetPowerPoint() int32 {
	if x != nil {
		return x.PowerPoint
	}
	return 0
}

func (x *PokemonInventorySkillRelation) GetUse() int32 {
	if x != nil {
		return x.Use
	}
	return 0
}

var File_pokemon_pokemon_inventory_skill_relation_proto protoreflect.FileDescriptor

const file_pokemon_pokemon_inventory_skill_relation_proto_rawDesc = "" +
	"\n" +
	".pokemon/pokemon_inventory_skill_relation.proto\x12\apokemon\x1a\x1fpokemon/pokemon_inventory.proto\x1a\x13pokemon/skill.proto\"\xd4\x01\n" +
	"\x1dPokemonInventorySkillRelation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12F\n" +
	"\x11pokemon_inventory\x18\x02 \x01(\v2\x19.pokemon.PokemonInventoryR\x10pokemonInventory\x12$\n" +
	"\x05skill\x18\x03 \x01(\v2\x0e.pokemon.SkillR\x05skill\x12\x1f\n" +
	"\vpower_point\x18\x04 \x01(\x05R\n" +
	"powerPoint\x12\x10\n" +
	"\x03use\x18\x05 \x01(\x05R\x03useB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_pokemon_inventory_skill_relation_proto_rawDescOnce sync.Once
	file_pokemon_pokemon_inventory_skill_relation_proto_rawDescData []byte
)

func file_pokemon_pokemon_inventory_skill_relation_proto_rawDescGZIP() []byte {
	file_pokemon_pokemon_inventory_skill_relation_proto_rawDescOnce.Do(func() {
		file_pokemon_pokemon_inventory_skill_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_inventory_skill_relation_proto_rawDesc), len(file_pokemon_pokemon_inventory_skill_relation_proto_rawDesc)))
	})
	return file_pokemon_pokemon_inventory_skill_relation_proto_rawDescData
}

var file_pokemon_pokemon_inventory_skill_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_pokemon_inventory_skill_relation_proto_goTypes = []any{
	(*PokemonInventorySkillRelation)(nil), // 0: pokemon.PokemonInventorySkillRelation
	(*PokemonInventory)(nil),              // 1: pokemon.PokemonInventory
	(*Skill)(nil),                         // 2: pokemon.Skill
}
var file_pokemon_pokemon_inventory_skill_relation_proto_depIdxs = []int32{
	1, // 0: pokemon.PokemonInventorySkillRelation.pokemon_inventory:type_name -> pokemon.PokemonInventory
	2, // 1: pokemon.PokemonInventorySkillRelation.skill:type_name -> pokemon.Skill
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pokemon_pokemon_inventory_skill_relation_proto_init() }
func file_pokemon_pokemon_inventory_skill_relation_proto_init() {
	if File_pokemon_pokemon_inventory_skill_relation_proto != nil {
		return
	}
	file_pokemon_pokemon_inventory_proto_init()
	file_pokemon_skill_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_inventory_skill_relation_proto_rawDesc), len(file_pokemon_pokemon_inventory_skill_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_pokemon_inventory_skill_relation_proto_goTypes,
		DependencyIndexes: file_pokemon_pokemon_inventory_skill_relation_proto_depIdxs,
		MessageInfos:      file_pokemon_pokemon_inventory_skill_relation_proto_msgTypes,
	}.Build()
	File_pokemon_pokemon_inventory_skill_relation_proto = out.File
	file_pokemon_pokemon_inventory_skill_relation_proto_goTypes = nil
	file_pokemon_pokemon_inventory_skill_relation_proto_depIdxs = nil
}
