// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/pokemon_inventory.proto

package pokemon

import (
	item "Pokemon/proto_go/item"
	user "Pokemon/proto_go/user"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	User          *user.User             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Pokemon       *Pokemon               `protobuf:"bytes,3,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	Item          *item.Item             `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Intimacy      int32                  `protobuf:"varint,6,opt,name=intimacy,proto3" json:"intimacy,omitempty"`
	Level         int32                  `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int32                  `protobuf:"varint,8,opt,name=exp,proto3" json:"exp,omitempty"`
	Hp            int32                  `protobuf:"varint,9,opt,name=hp,proto3" json:"hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonInventory) Reset() {
	*x = PokemonInventory{}
	mi := &file_pokemon_pokemon_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonInventory) ProtoMessage() {}

func (x *PokemonInventory) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_pokemon_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonInventory.ProtoReflect.Descriptor instead.
func (*PokemonInventory) Descriptor() ([]byte, []int) {
	return file_pokemon_pokemon_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonInventory) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PokemonInventory) GetUser() *user.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PokemonInventory) GetPokemon() *Pokemon {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *PokemonInventory) GetItem() *item.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *PokemonInventory) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PokemonInventory) GetIntimacy() int32 {
	if x != nil {
		return x.Intimacy
	}
	return 0
}

func (x *PokemonInventory) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PokemonInventory) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PokemonInventory) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

var File_pokemon_pokemon_inventory_proto protoreflect.FileDescriptor

const file_pokemon_pokemon_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1fpokemon/pokemon_inventory.proto\x12\apokemon\x1a\x0fuser/user.proto\x1a\x15pokemon/pokemon.proto\x1a\x0fitem/item.proto\"\xfd\x01\n" +
	"\x10PokemonInventory\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".user.UserR\x04user\x12*\n" +
	"\apokemon\x18\x03 \x01(\v2\x10.pokemon.PokemonR\apokemon\x12!\n" +
	"\x04item\x18\x04 \x01(\v2\r.pokemon.ItemR\x04item\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x1a\n" +
	"\bintimacy\x18\x06 \x01(\x05R\bintimacy\x12\x14\n" +
	"\x05level\x18\a \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\b \x01(\x05R\x03exp\x12\x0e\n" +
	"\x02hp\x18\t \x01(\x05R\x02hpB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_pokemon_inventory_proto_rawDescOnce sync.Once
	file_pokemon_pokemon_inventory_proto_rawDescData []byte
)

func file_pokemon_pokemon_inventory_proto_rawDescGZIP() []byte {
	file_pokemon_pokemon_inventory_proto_rawDescOnce.Do(func() {
		file_pokemon_pokemon_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_inventory_proto_rawDesc), len(file_pokemon_pokemon_inventory_proto_rawDesc)))
	})
	return file_pokemon_pokemon_inventory_proto_rawDescData
}

var file_pokemon_pokemon_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_pokemon_inventory_proto_goTypes = []any{
	(*PokemonInventory)(nil), // 0: pokemon.PokemonInventory
	(*user.User)(nil),        // 1: user.User
	(*Pokemon)(nil),          // 2: pokemon.Pokemon
	(*item.Item)(nil),        // 3: pokemon.Item
}
var file_pokemon_pokemon_inventory_proto_depIdxs = []int32{
	1, // 0: pokemon.PokemonInventory.user:type_name -> user.User
	2, // 1: pokemon.PokemonInventory.pokemon:type_name -> pokemon.Pokemon
	3, // 2: pokemon.PokemonInventory.item:type_name -> pokemon.Item
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pokemon_pokemon_inventory_proto_init() }
func file_pokemon_pokemon_inventory_proto_init() {
	if File_pokemon_pokemon_inventory_proto != nil {
		return
	}
	file_pokemon_pokemon_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_inventory_proto_rawDesc), len(file_pokemon_pokemon_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_pokemon_inventory_proto_goTypes,
		DependencyIndexes: file_pokemon_pokemon_inventory_proto_depIdxs,
		MessageInfos:      file_pokemon_pokemon_inventory_proto_msgTypes,
	}.Build()
	File_pokemon_pokemon_inventory_proto = out.File
	file_pokemon_pokemon_inventory_proto_goTypes = nil
	file_pokemon_pokemon_inventory_proto_depIdxs = nil
}
