// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/pokemon_type_relation.proto

package pokemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PokemonTypeRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pokemon       *Pokemon               `protobuf:"bytes,2,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	Type          *PokemonType           `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PokemonTypeRelation) Reset() {
	*x = PokemonTypeRelation{}
	mi := &file_pokemon_pokemon_type_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PokemonTypeRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PokemonTypeRelation) ProtoMessage() {}

func (x *PokemonTypeRelation) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_pokemon_type_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PokemonTypeRelation.ProtoReflect.Descriptor instead.
func (*PokemonTypeRelation) Descriptor() ([]byte, []int) {
	return file_pokemon_pokemon_type_relation_proto_rawDescGZIP(), []int{0}
}

func (x *PokemonTypeRelation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PokemonTypeRelation) GetPokemon() *Pokemon {
	if x != nil {
		return x.Pokemon
	}
	return nil
}

func (x *PokemonTypeRelation) GetType() *PokemonType {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_pokemon_pokemon_type_relation_proto protoreflect.FileDescriptor

const file_pokemon_pokemon_type_relation_proto_rawDesc = "" +
	"\n" +
	"#pokemon/pokemon_type_relation.proto\x12\apokemon\x1a\x15pokemon/pokemon.proto\x1a\x1apokemon/pokemon_type.proto\"\x7f\n" +
	"\x13PokemonTypeRelation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\apokemon\x18\x02 \x01(\v2\x10.pokemon.PokemonR\apokemon\x12(\n" +
	"\x04type\x18\x03 \x01(\v2\x14.pokemon.PokemonTypeR\x04typeB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_pokemon_type_relation_proto_rawDescOnce sync.Once
	file_pokemon_pokemon_type_relation_proto_rawDescData []byte
)

func file_pokemon_pokemon_type_relation_proto_rawDescGZIP() []byte {
	file_pokemon_pokemon_type_relation_proto_rawDescOnce.Do(func() {
		file_pokemon_pokemon_type_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_type_relation_proto_rawDesc), len(file_pokemon_pokemon_type_relation_proto_rawDesc)))
	})
	return file_pokemon_pokemon_type_relation_proto_rawDescData
}

var file_pokemon_pokemon_type_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_pokemon_type_relation_proto_goTypes = []any{
	(*PokemonTypeRelation)(nil), // 0: pokemon.PokemonTypeRelation
	(*Pokemon)(nil),             // 1: pokemon.Pokemon
	(*PokemonType)(nil),         // 2: pokemon.PokemonType
}
var file_pokemon_pokemon_type_relation_proto_depIdxs = []int32{
	1, // 0: pokemon.PokemonTypeRelation.pokemon:type_name -> pokemon.Pokemon
	2, // 1: pokemon.PokemonTypeRelation.type:type_name -> pokemon.PokemonType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pokemon_pokemon_type_relation_proto_init() }
func file_pokemon_pokemon_type_relation_proto_init() {
	if File_pokemon_pokemon_type_relation_proto != nil {
		return
	}
	file_pokemon_pokemon_proto_init()
	file_pokemon_pokemon_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_pokemon_type_relation_proto_rawDesc), len(file_pokemon_pokemon_type_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_pokemon_type_relation_proto_goTypes,
		DependencyIndexes: file_pokemon_pokemon_type_relation_proto_depIdxs,
		MessageInfos:      file_pokemon_pokemon_type_relation_proto_msgTypes,
	}.Build()
	File_pokemon_pokemon_type_relation_proto = out.File
	file_pokemon_pokemon_type_relation_proto_goTypes = nil
	file_pokemon_pokemon_type_relation_proto_depIdxs = nil
}
