// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/skill.proto

package pokemon

import (
	server "Pokemon/proto_go/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *server.Language       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Damage        float32                `protobuf:"fixed32,3,opt,name=damage,proto3" json:"damage,omitempty"`
	Accuracy      float32                `protobuf:"fixed32,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Type          *SkillType             `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Division      *SkillDivision         `protobuf:"bytes,6,opt,name=division,proto3" json:"division,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_pokemon_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_pokemon_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Skill) GetName() *server.Language {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Skill) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Skill) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Skill) GetType() *SkillType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Skill) GetDivision() *SkillDivision {
	if x != nil {
		return x.Division
	}
	return nil
}

func (x *Skill) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_pokemon_skill_proto protoreflect.FileDescriptor

const file_pokemon_skill_proto_rawDesc = "" +
	"\n" +
	"\x13pokemon/skill.proto\x12\apokemon\x1a\x15server/language.proto\x1a\x18pokemon/skill_type.proto\x1a\x1cpokemon/skill_division.proto\"\xed\x01\n" +
	"\x05Skill\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12$\n" +
	"\x04name\x18\x02 \x01(\v2\x10.server.LanguageR\x04name\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x02R\x06damage\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x02R\baccuracy\x12&\n" +
	"\x04type\x18\x05 \x01(\v2\x12.pokemon.SkillTypeR\x04type\x122\n" +
	"\bdivision\x18\x06 \x01(\v2\x16.pokemon.SkillDivisionR\bdivision\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriorityB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_skill_proto_rawDescOnce sync.Once
	file_pokemon_skill_proto_rawDescData []byte
)

func file_pokemon_skill_proto_rawDescGZIP() []byte {
	file_pokemon_skill_proto_rawDescOnce.Do(func() {
		file_pokemon_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_skill_proto_rawDesc), len(file_pokemon_skill_proto_rawDesc)))
	})
	return file_pokemon_skill_proto_rawDescData
}

var file_pokemon_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_skill_proto_goTypes = []any{
	(*Skill)(nil),           // 0: pokemon.Skill
	(*server.Language)(nil), // 1: server.Language
	(*SkillType)(nil),       // 2: pokemon.SkillType
	(*SkillDivision)(nil),   // 3: pokemon.SkillDivision
}
var file_pokemon_skill_proto_depIdxs = []int32{
	1, // 0: pokemon.Skill.name:type_name -> server.Language
	2, // 1: pokemon.Skill.type:type_name -> pokemon.SkillType
	3, // 2: pokemon.Skill.division:type_name -> pokemon.SkillDivision
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pokemon_skill_proto_init() }
func file_pokemon_skill_proto_init() {
	if File_pokemon_skill_proto != nil {
		return
	}
	file_pokemon_skill_type_proto_init()
	file_pokemon_skill_division_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_skill_proto_rawDesc), len(file_pokemon_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_skill_proto_goTypes,
		DependencyIndexes: file_pokemon_skill_proto_depIdxs,
		MessageInfos:      file_pokemon_skill_proto_msgTypes,
	}.Build()
	File_pokemon_skill_proto = out.File
	file_pokemon_skill_proto_goTypes = nil
	file_pokemon_skill_proto_depIdxs = nil
}
