// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pokemon/skill_type.proto

package pokemon

import (
	server "Pokemon/proto_go/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *server.Language       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillType) Reset() {
	*x = SkillType{}
	mi := &file_pokemon_skill_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillType) ProtoMessage() {}

func (x *SkillType) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_skill_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillType.ProtoReflect.Descriptor instead.
func (*SkillType) Descriptor() ([]byte, []int) {
	return file_pokemon_skill_type_proto_rawDescGZIP(), []int{0}
}

func (x *SkillType) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SkillType) GetName() *server.Language {
	if x != nil {
		return x.Name
	}
	return nil
}

var File_pokemon_skill_type_proto protoreflect.FileDescriptor

const file_pokemon_skill_type_proto_rawDesc = "" +
	"\n" +
	"\x18pokemon/skill_type.proto\x12\apokemon\x1a\x15server/language.proto\"E\n" +
	"\tSkillType\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12$\n" +
	"\x04name\x18\x02 \x01(\v2\x10.server.LanguageR\x04nameB\x1aZ\x18Pokemon/proto_go/pokemonb\x06proto3"

var (
	file_pokemon_skill_type_proto_rawDescOnce sync.Once
	file_pokemon_skill_type_proto_rawDescData []byte
)

func file_pokemon_skill_type_proto_rawDescGZIP() []byte {
	file_pokemon_skill_type_proto_rawDescOnce.Do(func() {
		file_pokemon_skill_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_skill_type_proto_rawDesc), len(file_pokemon_skill_type_proto_rawDesc)))
	})
	return file_pokemon_skill_type_proto_rawDescData
}

var file_pokemon_skill_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pokemon_skill_type_proto_goTypes = []any{
	(*SkillType)(nil),       // 0: pokemon.SkillType
	(*server.Language)(nil), // 1: server.Language
}
var file_pokemon_skill_type_proto_depIdxs = []int32{
	1, // 0: pokemon.SkillType.name:type_name -> server.Language
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pokemon_skill_type_proto_init() }
func file_pokemon_skill_type_proto_init() {
	if File_pokemon_skill_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_skill_type_proto_rawDesc), len(file_pokemon_skill_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pokemon_skill_type_proto_goTypes,
		DependencyIndexes: file_pokemon_skill_type_proto_depIdxs,
		MessageInfos:      file_pokemon_skill_type_proto_msgTypes,
	}.Build()
	File_pokemon_skill_type_proto = out.File
	file_pokemon_skill_type_proto_goTypes = nil
	file_pokemon_skill_type_proto_depIdxs = nil
}
