// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: server/client.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ClientStatus  int32                  `protobuf:"varint,2,opt,name=client_status,json=clientStatus,proto3" json:"client_status,omitempty"`
	ServerStatus  int32                  `protobuf:"varint,3,opt,name=server_status,json=serverStatus,proto3" json:"server_status,omitempty"`
	ClientVersion string                 `protobuf:"bytes,4,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ServerVersion string                 `protobuf:"bytes,5,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ServerCdn     string                 `protobuf:"bytes,8,opt,name=server_cdn,json=serverCdn,proto3" json:"server_cdn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_server_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Client) GetClientStatus() int32 {
	if x != nil {
		return x.ClientStatus
	}
	return 0
}

func (x *Client) GetServerStatus() int32 {
	if x != nil {
		return x.ServerStatus
	}
	return 0
}

func (x *Client) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Client) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Client) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Client) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Client) GetServerCdn() string {
	if x != nil {
		return x.ServerCdn
	}
	return ""
}

var File_server_client_proto protoreflect.FileDescriptor

const file_server_client_proto_rawDesc = "" +
	"\n" +
	"\x13server/client.proto\x12\x06server\"\x91\x02\n" +
	"\x06Client\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12#\n" +
	"\rclient_status\x18\x02 \x01(\x05R\fclientStatus\x12#\n" +
	"\rserver_status\x18\x03 \x01(\x05R\fserverStatus\x12%\n" +
	"\x0eclient_version\x18\x04 \x01(\tR\rclientVersion\x12%\n" +
	"\x0eserver_version\x18\x05 \x01(\tR\rserverVersion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"server_cdn\x18\b \x01(\tR\tserverCdnB\x19Z\x17Pokemon/proto_go/serverb\x06proto3"

var (
	file_server_client_proto_rawDescOnce sync.Once
	file_server_client_proto_rawDescData []byte
)

func file_server_client_proto_rawDescGZIP() []byte {
	file_server_client_proto_rawDescOnce.Do(func() {
		file_server_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_client_proto_rawDesc), len(file_server_client_proto_rawDesc)))
	})
	return file_server_client_proto_rawDescData
}

var file_server_client_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_client_proto_goTypes = []any{
	(*Client)(nil), // 0: server.Client
}
var file_server_client_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_client_proto_init() }
func file_server_client_proto_init() {
	if File_server_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_client_proto_rawDesc), len(file_server_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_client_proto_goTypes,
		DependencyIndexes: file_server_client_proto_depIdxs,
		MessageInfos:      file_server_client_proto_msgTypes,
	}.Build()
	File_server_client_proto = out.File
	file_server_client_proto_goTypes = nil
	file_server_client_proto_depIdxs = nil
}
