// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: server/language.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Kor           string                 `protobuf:"bytes,2,opt,name=kor,proto3" json:"kor,omitempty"`
	En            string                 `protobuf:"bytes,3,opt,name=en,proto3" json:"en,omitempty"`
	Cn            string                 `protobuf:"bytes,4,opt,name=cn,proto3" json:"cn,omitempty"`
	Jp            string                 `protobuf:"bytes,5,opt,name=jp,proto3" json:"jp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_server_language_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_server_language_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_server_language_proto_rawDescGZIP(), []int{0}
}

func (x *Language) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Language) GetKor() string {
	if x != nil {
		return x.Kor
	}
	return ""
}

func (x *Language) GetEn() string {
	if x != nil {
		return x.En
	}
	return ""
}

func (x *Language) GetCn() string {
	if x != nil {
		return x.Cn
	}
	return ""
}

func (x *Language) GetJp() string {
	if x != nil {
		return x.Jp
	}
	return ""
}

var File_server_language_proto protoreflect.FileDescriptor

const file_server_language_proto_rawDesc = "" +
	"\n" +
	"\x15server/language.proto\x12\x06server\"`\n" +
	"\bLanguage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03kor\x18\x02 \x01(\tR\x03kor\x12\x0e\n" +
	"\x02en\x18\x03 \x01(\tR\x02en\x12\x0e\n" +
	"\x02cn\x18\x04 \x01(\tR\x02cn\x12\x0e\n" +
	"\x02jp\x18\x05 \x01(\tR\x02jpB\x19Z\x17Pokemon/proto_go/serverb\x06proto3"

var (
	file_server_language_proto_rawDescOnce sync.Once
	file_server_language_proto_rawDescData []byte
)

func file_server_language_proto_rawDescGZIP() []byte {
	file_server_language_proto_rawDescOnce.Do(func() {
		file_server_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_language_proto_rawDesc), len(file_server_language_proto_rawDesc)))
	})
	return file_server_language_proto_rawDescData
}

var file_server_language_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_language_proto_goTypes = []any{
	(*Language)(nil), // 0: server.Language
}
var file_server_language_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_language_proto_init() }
func file_server_language_proto_init() {
	if File_server_language_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_language_proto_rawDesc), len(file_server_language_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_language_proto_goTypes,
		DependencyIndexes: file_server_language_proto_depIdxs,
		MessageInfos:      file_server_language_proto_msgTypes,
	}.Build()
	File_server_language_proto = out.File
	file_server_language_proto_goTypes = nil
	file_server_language_proto_depIdxs = nil
}
