// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: server/npc.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Npc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          *Language              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Npc) Reset() {
	*x = Npc{}
	mi := &file_server_npc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Npc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Npc) ProtoMessage() {}

func (x *Npc) ProtoReflect() protoreflect.Message {
	mi := &file_server_npc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Npc.ProtoReflect.Descriptor instead.
func (*Npc) Descriptor() ([]byte, []int) {
	return file_server_npc_proto_rawDescGZIP(), []int{0}
}

func (x *Npc) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Npc) GetName() *Language {
	if x != nil {
		return x.Name
	}
	return nil
}

var File_server_npc_proto protoreflect.FileDescriptor

const file_server_npc_proto_rawDesc = "" +
	"\n" +
	"\x10server/npc.proto\x12\x06server\x1a\x15server/language.proto\"?\n" +
	"\x03Npc\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12$\n" +
	"\x04name\x18\x02 \x01(\v2\x10.server.LanguageR\x04nameB\x19Z\x17Pokemon/proto_go/serverb\x06proto3"

var (
	file_server_npc_proto_rawDescOnce sync.Once
	file_server_npc_proto_rawDescData []byte
)

func file_server_npc_proto_rawDescGZIP() []byte {
	file_server_npc_proto_rawDescOnce.Do(func() {
		file_server_npc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_npc_proto_rawDesc), len(file_server_npc_proto_rawDesc)))
	})
	return file_server_npc_proto_rawDescData
}

var file_server_npc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_npc_proto_goTypes = []any{
	(*Npc)(nil),      // 0: server.Npc
	(*Language)(nil), // 1: server.Language
}
var file_server_npc_proto_depIdxs = []int32{
	1, // 0: server.Npc.name:type_name -> server.Language
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_npc_proto_init() }
func file_server_npc_proto_init() {
	if File_server_npc_proto != nil {
		return
	}
	file_server_language_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_npc_proto_rawDesc), len(file_server_npc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_npc_proto_goTypes,
		DependencyIndexes: file_server_npc_proto_depIdxs,
		MessageInfos:      file_server_npc_proto_msgTypes,
	}.Build()
	File_server_npc_proto = out.File
	file_server_npc_proto_goTypes = nil
	file_server_npc_proto_depIdxs = nil
}
