// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user/blacklist.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlackList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       int64                  `protobuf:"varint,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlackList) Reset() {
	*x = BlackList{}
	mi := &file_user_blacklist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackList) ProtoMessage() {}

func (x *BlackList) ProtoReflect() protoreflect.Message {
	mi := &file_user_blacklist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackList.ProtoReflect.Descriptor instead.
func (*BlackList) Descriptor() ([]byte, []int) {
	return file_user_blacklist_proto_rawDescGZIP(), []int{0}
}

func (x *BlackList) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BlackList) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BlackList) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BlackList) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BlackList) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *BlackList) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

var File_user_blacklist_proto protoreflect.FileDescriptor

const file_user_blacklist_proto_rawDesc = "" +
	"\n" +
	"\x14user/blacklist.proto\x12\x04user\x1a\x0fuser/user.proto\"\xba\x01\n" +
	"\tBlackList\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".user.UserR\x04user\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x06 \x01(\x03R\aendedAtB\x17Z\x15Pokemon/proto_go/userb\x06proto3"

var (
	file_user_blacklist_proto_rawDescOnce sync.Once
	file_user_blacklist_proto_rawDescData []byte
)

func file_user_blacklist_proto_rawDescGZIP() []byte {
	file_user_blacklist_proto_rawDescOnce.Do(func() {
		file_user_blacklist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_blacklist_proto_rawDesc), len(file_user_blacklist_proto_rawDesc)))
	})
	return file_user_blacklist_proto_rawDescData
}

var file_user_blacklist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_blacklist_proto_goTypes = []any{
	(*BlackList)(nil), // 0: user.BlackList
	(*User)(nil),      // 1: user.User
}
var file_user_blacklist_proto_depIdxs = []int32{
	1, // 0: user.BlackList.user:type_name -> user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_blacklist_proto_init() }
func file_user_blacklist_proto_init() {
	if File_user_blacklist_proto != nil {
		return
	}
	file_user_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_blacklist_proto_rawDesc), len(file_user_blacklist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_blacklist_proto_goTypes,
		DependencyIndexes: file_user_blacklist_proto_depIdxs,
		MessageInfos:      file_user_blacklist_proto_msgTypes,
	}.Build()
	File_user_blacklist_proto = out.File
	file_user_blacklist_proto_goTypes = nil
	file_user_blacklist_proto_depIdxs = nil
}
