// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user/story_flag_user_relation.proto

package user

import (
	server "Pokemon/proto_go/server"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoryFlagUserRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	StoryFlag     *server.StoryFlag      `protobuf:"bytes,3,opt,name=story_flag,json=storyFlag,proto3" json:"story_flag,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryFlagUserRelation) Reset() {
	*x = StoryFlagUserRelation{}
	mi := &file_user_story_flag_user_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryFlagUserRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryFlagUserRelation) ProtoMessage() {}

func (x *StoryFlagUserRelation) ProtoReflect() protoreflect.Message {
	mi := &file_user_story_flag_user_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryFlagUserRelation.ProtoReflect.Descriptor instead.
func (*StoryFlagUserRelation) Descriptor() ([]byte, []int) {
	return file_user_story_flag_user_relation_proto_rawDescGZIP(), []int{0}
}

func (x *StoryFlagUserRelation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StoryFlagUserRelation) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *StoryFlagUserRelation) GetStoryFlag() *server.StoryFlag {
	if x != nil {
		return x.StoryFlag
	}
	return nil
}

func (x *StoryFlagUserRelation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_user_story_flag_user_relation_proto protoreflect.FileDescriptor

const file_user_story_flag_user_relation_proto_rawDesc = "" +
	"\n" +
	"#user/story_flag_user_relation.proto\x12\x04user\x1a\x0fuser/user.proto\x1a\x17server/story_flag.proto\"\x9c\x01\n" +
	"\x15StoryFlagUserRelation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1e\n" +
	"\x04user\x18\x02 \x01(\v2\n" +
	".user.UserR\x04user\x120\n" +
	"\n" +
	"story_flag\x18\x03 \x01(\v2\x11.server.StoryFlagR\tstoryFlag\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAtB\x17Z\x15Pokemon/proto_go/userb\x06proto3"

var (
	file_user_story_flag_user_relation_proto_rawDescOnce sync.Once
	file_user_story_flag_user_relation_proto_rawDescData []byte
)

func file_user_story_flag_user_relation_proto_rawDescGZIP() []byte {
	file_user_story_flag_user_relation_proto_rawDescOnce.Do(func() {
		file_user_story_flag_user_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_story_flag_user_relation_proto_rawDesc), len(file_user_story_flag_user_relation_proto_rawDesc)))
	})
	return file_user_story_flag_user_relation_proto_rawDescData
}

var file_user_story_flag_user_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_story_flag_user_relation_proto_goTypes = []any{
	(*StoryFlagUserRelation)(nil), // 0: user.StoryFlagUserRelation
	(*User)(nil),                  // 1: user.User
	(*server.StoryFlag)(nil),      // 2: server.StoryFlag
}
var file_user_story_flag_user_relation_proto_depIdxs = []int32{
	1, // 0: user.StoryFlagUserRelation.user:type_name -> user.User
	2, // 1: user.StoryFlagUserRelation.story_flag:type_name -> server.StoryFlag
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_story_flag_user_relation_proto_init() }
func file_user_story_flag_user_relation_proto_init() {
	if File_user_story_flag_user_relation_proto != nil {
		return
	}
	file_user_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_story_flag_user_relation_proto_rawDesc), len(file_user_story_flag_user_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_story_flag_user_relation_proto_goTypes,
		DependencyIndexes: file_user_story_flag_user_relation_proto_depIdxs,
		MessageInfos:      file_user_story_flag_user_relation_proto_msgTypes,
	}.Build()
	File_user_story_flag_user_relation_proto = out.File
	file_user_story_flag_user_relation_proto_goTypes = nil
	file_user_story_flag_user_relation_proto_depIdxs = nil
}
